url: ""
baseurl: ""
theme: null

# google:
#   tracking_id:
#   container_id:

# cloudflare:
#   token:

collections:
  services:
    output: false
  portfolio:
    output: false
  about:
    output: false
  team:
    output: false
  logos:
    output: false
  introduction:
    output: false